basePath: /v1/comment
definitions:
  httputil.HTTPError400:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  httputil.HTTPError404:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status not found
        type: string
    type: object
  httputil.HTTPError405:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: status method not allowed
        type: string
    type: object
  httputil.HTTPError408:
    properties:
      code:
        example: 408
        type: integer
      message:
        example: status request timeout
        type: string
    type: object
  httputil.HTTPError500:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: status internal server error
        type: string
    type: object
  httputil.HTTPError503:
    properties:
      code:
        example: 503
        type: integer
      message:
        example: status service unavailable
        type: string
    type: object
  httputil.HTTPError505:
    properties:
      code:
        example: 505
        type: integer
      message:
        example: status HTTP version not supported
        type: string
    type: object
  models.AddCommentRequestBody:
    properties:
      author:
        type: string
      id:
        description: gorm.Model
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
  models.Comment:
    properties:
      author:
        type: string
      id:
        description: gorm.Model        // adds ID, Title, Author & Slug
        type: string
      slug:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample CRUD HTTP service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 'CloudNua: Comment Service'
  version: "1.0"
paths:
  /comments:
    get:
      consumes:
      - application/json
      description: get comments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Comment'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError404'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/httputil.HTTPError405'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/httputil.HTTPError408'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError500'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.HTTPError503'
        "505":
          description: HTTP Version Not Supported
          schema:
            $ref: '#/definitions/httputil.HTTPError505'
      summary: List Comments
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: add by json comment
      parameters:
      - description: Add comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/models.AddCommentRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError404'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/httputil.HTTPError405'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/httputil.HTTPError408'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError500'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/httputil.HTTPError503'
        "505":
          description: HTTP Version Not Supported
          schema:
            $ref: '#/definitions/httputil.HTTPError505'
      summary: Add a comment
      tags:
      - comments
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
